# Behaviorbot config. See https://github.com/behaviorbot/ for more information.
# Note: Please Don't edit this file directly.
# Edit https://github.com/benbalter/shared-community-files instead.

# Configuration for update-docs - https://github.com/behaviorbot/update-docs
updateDocsComment: "Thanks for the pull request! If you are making any changes to the user-facing functionality, please be sure to update the documentation in the `README` or `docs/` folder alongside your change. :heart:"

# Configuration for request-info - https://github.com/behaviorbot/request-info
requestInfoReplyComment: Thanks for this. Do you mind providing a bit more information about what problem you're trying to solve?
requestInfoLabelToAdd: more-information-needed

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
#newIssueWelcomeComment: >
#  Welcome!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
newPRWelcomeComment: Welcome! Congrats on your first pull request to Jekyll Remote Theme. If you haven't already, please be sure to check out [the contributing guidelines](https://github.com/benbalter/jekyll-remote-theme/blob/master/docs/CONTRIBUTING.md).

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
firstPRMergeComment: "Congrats on getting your first pull request to Jekyll Remote Theme merged! Without amazing humans like you submitting pull requests, we couldn’t run this project. You rock! :tada:<br /><br />If you're interested in tackling another bug or feature, take a look at [the open issues](https://github.com/benbalter/jekyll-remote-theme/issues), especially those [labeled `help wanted`](https://github.com/benbalter/jekyll-remote-theme/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)."

# Bug workaround
contact_links: []
gems:
  - jekyll-remote-theme

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-remote-theme
  
remote_theme: https://github.com/benbalter/retlab

title: South Reusable Assets
description: A shared repository including business use cases and code snippets with fully enclosed AI projects that can be repurposed entirely or in part by your architects and technical project resources covering all facets of Azure AI including OpenAI, AzureML and AI Search.

lang: en-US

# Pages to include in header navigation
nav_pages:
  - index.html
  - talks.md
  - press.md
  - about.md
  - contact.md

# Pages to include in footer navigation
footer_pages:
  - books.md
  - fine-print.md


# Links to include on the contact page
contact_links:
  - name: Twitter
    url: https://twitter.com/laura_e_edell
    icon: twitter
  - name: LinkedIn
    url: https://linkedin.com/in/lauraerinedell
    icon: linkedin

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      comments: false


